"""add avg_rounds_pd to matatus table

Revision ID: 392080708072
Revises: 537d9eb4d5f0
Create Date: 2023-09-07 01:59:19.387267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392080708072'
down_revision: Union[str, None] = '537d9eb4d5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matatus', sa.Column('avg_rounds_pd', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_members_name'), 'members', ['name'], unique=False)
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_index(op.f('ix_members_name'), table_name='members')
    op.drop_column('matatus', 'avg_rounds_pd')
    # ### end Alembic commands ###
