"""add driver_name & contact columns to matatus table

Revision ID: 5ec007ef6b94
Revises: 392080708072
Create Date: 2023-09-07 02:16:40.267474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec007ef6b94'
down_revision: Union[str, None] = '392080708072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matatus', sa.Column('driver_name', sa.String(), nullable=True))
    op.add_column('matatus', sa.Column('driver_contact', sa.Integer(), nullable=True))
    op.drop_index('ix_members_name', table_name='members')
    op.create_index(op.f('ix_members_name'), 'members', ['name'], unique=False)
    op.drop_index('ix_routes_name', table_name='routes')
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.create_index('ix_routes_name', 'routes', ['name'], unique=False)
    op.drop_index(op.f('ix_members_name'), table_name='members')
    op.create_index('ix_members_name', 'members', ['name'], unique=False)
    op.drop_column('matatus', 'driver_contact')
    op.drop_column('matatus', 'driver_name')
    # ### end Alembic commands ###
